version: "3"
services:
  db:
    container_name: meus_pacientes_db
    restart: always
    image: postgres:16.2-alpine
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
    ports:
      - "${POSTGRES_PORT}:5432"
  app:
    container_name: meus_pacientes_app
    restart: always
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/app
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - MASTER_KEY=${MASTER_KEY}
      - POSTGRES_HOST=${POSTGRES_HOST:?nome do host}
      - POSTGRES_NAME=${POSTGRES_NAME:?nome do BD ausente}
      - POSTGRES_USER=${POSTGRES_USER:?usuario do BD ausente}
      - POSTGRES_PASS=${POSTGRES_PASS:?senha do BD ausente}
    ports:
      - "${API_PORT}:5000"
    depends_on:
      - db
  nginx:
    container_name: meus_pacientes_nginx
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "${APP_PORT}:80"
    depends_on:
      - app
