services:
  db-patients:
    image: mariadb:11.7.2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - patients
      - cloudbeaver
      - appsmith

  api:
    build: .
    ports:
      - "${API_PORT}:5000"
    environment:
      DATABASE_URL: "mysql://${DB_USER}:${DB_PASS}@db-patients:3306/${DB_NAME}"
    depends_on:
      - db-patients
    networks:
      - patients
      - appsmith

networks:
  patients:
    name: patients
    driver: bridge
  appsmith:
    name: appsmith-network
    external: true
  cloudbeaver:
    name: cloudbeaver
    external: true