services:
  app:
    container_name: esus-meus-pacientes
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - MASTER_KEY=${MASTER_KEY}

    volumes:
      - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
