"""initial schema

Revision ID: 3a718e58f046
Revises: 
Create Date: 2024-04-02 15:20:57.024393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a718e58f046'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cid10',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('comorbidities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('abbreviation', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('institutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('cnes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('cpf', sa.String(), nullable=True),
    sa.Column('cns', sa.String(), nullable=True),
    sa.Column('birthdate', sa.Date(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cns'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email')
    )
    op.create_table('_user_institution_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('institution_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('mother_name', sa.String(), nullable=True),
    sa.Column('sex', sa.Enum('male', 'fema', name='sexenum'), nullable=True),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('cpf', sa.String(), nullable=True),
    sa.Column('cns', sa.String(), nullable=True),
    sa.Column('rg', sa.String(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('institution_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cns'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('rg')
    )
    op.create_table('_patient_comorbidity',
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('comorbidity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['comorbidity_id'], ['comorbidities.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], )
    )
    op.create_table('_patient_user',
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('comorbidities_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('risk', sa.Enum('active', 'high', 'low', 'vhigh', 'vlow', 'no', name='riskenum'), nullable=False),
    sa.Column('last_visit', sa.Date(), nullable=True),
    sa.Column('observations', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('home_care_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('last_visit', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prescriptions_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origin', sa.Enum('capes', 'benzo', 'freepass', name='originenum'), nullable=False),
    sa.Column('dosage', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('observations', sa.String(), nullable=True),
    sa.Column('withdrawal_attempt', sa.String(), nullable=True),
    sa.Column('usage_time', sa.String(), nullable=True),
    sa.Column('last_renovation', sa.Date(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prescriptions_list')
    op.drop_table('home_care_list')
    op.drop_table('comorbidities_list')
    op.drop_table('_patient_user')
    op.drop_table('_patient_comorbidity')
    op.drop_table('patients')
    op.drop_table('_user_institution_roles')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('institutions')
    op.drop_table('comorbidities')
    op.drop_table('cid10')
    # ### end Alembic commands ###
