"""add timestamp to lat test arrival

Revision ID: 7c9d2e6962da
Revises: d9d54279dc91
Create Date: 2024-05-03 00:57:42.977086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c9d2e6962da'
down_revision = 'd9d54279dc91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lab_test_arrivals', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lab_test_arrivals', 'updated_at')
    # ### end Alembic commands ###
