"""empty message

Revision ID: 85560d9172a0
Revises: 3a718e58f046
Create Date: 2024-04-16 20:23:14.510849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85560d9172a0'
down_revision = '3a718e58f046'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prescriptions_list', sa.Column('las_prescription_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prescriptions_list', 'las_prescription_date')
    # ### end Alembic commands ###
