"""empty message

Revision ID: 94c5664ab660
Revises: 85560d9172a0
Create Date: 2024-04-16 20:23:40.975571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94c5664ab660'
down_revision = '85560d9172a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prescriptions_list', sa.Column('last_prescription_date', sa.Date(), nullable=True))
    op.drop_column('prescriptions_list', 'las_prescription_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prescriptions_list', sa.Column('las_prescription_date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('prescriptions_list', 'last_prescription_date')
    # ### end Alembic commands ###
