"""add lab test arrivals model

Revision ID: 9a536e29fad7
Revises: 94c5664ab660
Create Date: 2024-05-02 19:15:06.698957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a536e29fad7'
down_revision = '94c5664ab660'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lab_test_arrivals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('arrival_date', sa.Date(), nullable=False),
    sa.Column('lab_test_date', sa.Date(), nullable=False),
    sa.Column('pick_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lab_test_arrivals')
    # ### end Alembic commands ###
