"""rename pregnancy prop

Revision ID: bc4fc6bc39f3
Revises: ee1aee69e638
Create Date: 2024-07-07 18:20:31.471894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc4fc6bc39f3'
down_revision = 'ee1aee69e638'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pregnancies', 'day_of_birth', new_column_name='date_of_birth')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pregnancies', 'date_of_birth', new_column_name='day_of_birth')
    # ### end Alembic commands ###
