"""initial migration

Revision ID: ee1aee69e638
Revises:
Create Date: 2024-06-15 01:43:57.404167

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ee1aee69e638"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cid10",
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("code"),
    )
    op.create_table(
        "comorbidities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("abbreviation", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "institutions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("cnes", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "lab_tests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("abbreviation", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "risk_levels",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "roles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("password_hash", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("cpf", sa.String(), nullable=False),
        sa.Column("cns", sa.String(), nullable=True),
        sa.Column("dob", sa.Date(), nullable=False),
        sa.Column("phone", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cns"),
        sa.UniqueConstraint("cpf"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "_user_institution_roles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("institution_id", sa.Integer(), nullable=True),
        sa.Column("role_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["institution_id"],
            ["institutions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "patients",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("mother_name", sa.String(), nullable=True),
        sa.Column("sex", sa.Enum("male", "fema", name="sexenum"), nullable=True),
        sa.Column("dob", sa.Date(), nullable=True),
        sa.Column("cpf", sa.String(), nullable=True),
        sa.Column("cns", sa.String(), nullable=True),
        sa.Column("rg", sa.String(), nullable=True),
        sa.Column("weight_kg", sa.Float(), nullable=True),
        sa.Column("phone", sa.String(), nullable=True),
        sa.Column("institution_id", sa.Integer(), nullable=True),
        sa.Column("community_health_agent_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["community_health_agent_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["institution_id"],
            ["institutions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cns"),
        sa.UniqueConstraint("cpf"),
        sa.UniqueConstraint("rg"),
    )
    op.create_table(
        "_patient_comorbidity",
        sa.Column("patient_id", sa.Integer(), nullable=True),
        sa.Column("comorbidity_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["comorbidity_id"],
            ["comorbidities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
    )
    op.create_table(
        "active_targets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("patient_id", sa.Integer(), nullable=True),
        sa.Column("reason", sa.String(), nullable=True),
        sa.Column("evolution", sa.String(), nullable=True),
        sa.Column("resolution_date", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "continuous_prescriptions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dosage", sa.String(), nullable=True),
        sa.Column("reason", sa.String(), nullable=True),
        sa.Column("withdrawal_attempt", sa.String(), nullable=True),
        sa.Column("usage_time", sa.String(), nullable=True),
        sa.Column("last_renovation", sa.Date(), nullable=True),
        sa.Column("last_prescription_date", sa.Date(), nullable=True),
        sa.Column("patient_id", sa.Integer(), nullable=True),
        sa.Column("observations", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "home_care",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("patient_id", sa.Integer(), nullable=True),
        sa.Column("last_visit", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "lab_test_arrivals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("patient_id", sa.Integer(), nullable=True),
        sa.Column("arrival_date", sa.Date(), nullable=False),
        sa.Column("lab_test_date", sa.Date(), nullable=False),
        sa.Column("pick_date", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "patient_comorbidities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("patient_id", sa.Integer(), nullable=True),
        sa.Column("risk_id", sa.Integer(), nullable=True),
        sa.Column("last_visit", sa.Date(), nullable=True),
        sa.Column("observations", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["risk_id"],
            ["risk_levels.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "patient_lab_tests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("patient_id", sa.Integer(), nullable=True),
        sa.Column("lab_test_id", sa.Integer(), nullable=True),
        sa.Column("value", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["lab_test_id"],
            ["lab_tests.id"],
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pregnancies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("patient_id", sa.Integer(), nullable=True),
        sa.Column("parity", sa.String(), nullable=True),
        sa.Column("last_menstrual_period", sa.Date(), nullable=True),
        sa.Column("observations", sa.String(), nullable=True),
        sa.Column("risk_id", sa.Integer(), nullable=True),
        sa.Column("day_of_birth", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["risk_id"],
            ["risk_levels.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pregnancy_lab_tests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pregnancy_id", sa.Integer(), nullable=True),
        sa.Column("lab_test_id", sa.Integer(), nullable=True),
        sa.Column("value", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["lab_test_id"],
            ["lab_tests.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pregnancy_id"],
            ["pregnancies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ultrasonographies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=True),
        sa.Column("gestational_age_weeks", sa.Integer(), nullable=True),
        sa.Column("gestational_age_days", sa.Integer(), nullable=True),
        sa.Column("pregnancy_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["pregnancy_id"],
            ["pregnancies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ultrasonographies")
    op.drop_table("pregnancy_lab_tests")
    op.drop_table("pregnancies")
    op.drop_table("patient_lab_tests")
    op.drop_table("patient_comorbidities")
    op.drop_table("lab_test_arrivals")
    op.drop_table("home_care")
    op.drop_table("continuous_prescriptions")
    op.drop_table("active_targets")
    op.drop_table("_patient_comorbidity")
    op.drop_table("patients")
    op.drop_table("_user_institution_roles")
    op.drop_table("users")
    op.drop_table("roles")
    op.drop_table("risk_levels")
    op.drop_table("lab_tests")
    op.drop_table("institutions")
    op.drop_table("comorbidities")
    op.drop_table("cid10")
    # ### end Alembic commands ###
